import React, { createContext, useContext, useEffect, useState } from 'react';
import { smartTranslationService } from '../services/translationService';

type Language = 'ar' | 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  translateText: (text: string) => Promise<string>;
  translateProduct: (product: any) => Promise<any>;
  translateStore: (store: any) => Promise<any>;
  translateLiquid: (liquid: any) => Promise<any>;
}

const translations = {
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.products': 'المنتجات',
    'nav.stores': 'المتاجر',
    'nav.favorites': 'المفضلة',
    'nav.liquids': 'النكهات',
    'nav.mix': 'الخلط الذكي',
    
    // Categories
    'category.vape-kits': 'جهاز فايب متكامل',
    'category.vape-boxes': 'جهاز الفايب',
    'category.atomizers': 'الخزان',
    'category.pyrex': 'Pyrex',
    'category.accus': 'بطاريات الفايب',
    'category.accessories': 'إكسسوارات الفايب',
    'category.cotton': 'القطن',
    'category.coils': 'الكويل',
    'category.resistors': 'المقاومات',
    
    // Product details
    'product.addToCart': 'إضافة إلى السلة',
    'product.available': 'متوفر',
    'product.notAvailable': 'غير متوفر',
    'product.price': 'السعر',
    'product.stock': 'المخزون',
    'product.description': 'الوصف',
    'product.category': 'الفئة',
    'product.viewDetails': 'عرض التفاصيل',
    'product.outOfStock': 'نفذ من المخزون',
    'product.inStock': 'متوفر في المخزون',
    'product.pieces': 'قطعة',
    'product.notFound': 'المنتج غير موجود',
    'product.availableInStores': 'متوفر في المتاجر',
    'product.availableInBranches': 'متوفر في الفروع',
    
    // Store details
    'store.location': 'الموقع',
    'store.contact': 'التواصل',
    'store.directions': 'الاتجاهات',
    'store.workingHours': 'ساعات العمل',
    
    // Theme
    'theme.light': 'فاتح',
    'theme.dark': 'داكن',
    
    // Language
    'lang.ar': 'العربية',
    'lang.en': 'English',
    'lang.fr': 'Français',
    
    // Home
    'home.title': 'مرحبًا بك في متجر الفيب',
    'home.subtitle': 'كل ما تحتاجه للفيب في مكان واحد',
    'home.stores': 'فروعنا',
    'home.storesDesc': 'اعثر على أقرب فرع إليك',
    'home.products': 'المنتجات',
    'home.productsDesc': 'تصفح جميع الأجهزة والإكسسوارات',
    'home.liquids': 'النكهات والسوائل',
    'home.liquidsDesc': 'استكشف النكهات وامزج بنفسك',
    'home.welcome': 'مرحباً بك في',
    'home.vapeCapitole': 'Vape Capitole',
    'home.discover': 'اكتشف مجموعتنا الواسعة',
    'home.quality': 'جودة عالية وأسعار منافسة',
    
    // Footer
    'footer.title': 'متجر الفيب',
    'footer.subtitle': 'كل ما تحتاجه للفيب في مكان واحد',
    'footer.quickLinks': 'روابط سريعة',
    'footer.home': 'الرئيسية',
    'footer.products': 'المنتجات',
    'footer.liquids': 'النكهات',
    'footer.contact': 'تواصل معنا',
    'footer.email': 'البريد الإلكتروني',
    'footer.phone': 'الهاتف',
    'footer.rights': 'جميع الحقوق محفوظة.',
    'footer.followUs': 'تابعنا',
    'footer.newsletter': 'النشرة الإخبارية',
    'footer.subscribe': 'اشترك',
    'footer.subscribeDesc': 'احصل على آخر العروض والتحديثات',
    
    // Liquids & MixLiquids
    'liquids.title': 'النكهات والسوائل',
    'liquids.customMix': 'خلطة مخصصة',
    'liquids.customMixBtn': 'امزج بنفسك',
    'liquids.createMix': 'أنشئ خلطتك',
    'liquids.chooseFlavors': 'اختر النكهات (بحد أقصى 3)',
    'liquids.nicotine': 'مستوى النيكوتين',
    'liquids.volume': 'الحجم',
    'liquids.vgpg': 'نسبة VG/PG',
    'liquids.total': 'الإجمالي',
    'liquids.priceNote': 'سعر أساسي + 2 دج لكل نكهة إضافية',
    'liquids.addToCart': 'أضف إلى السلة',
    'liquids.noLiquids': 'لا توجد سوائل متاحة حالياً.',
    'liquids.flavors': 'النكهات',
    'liquids.inStock': 'متوفر',
    'liquids.outOfStock': 'غير متوفر',
    'liquids.viewAll': 'عرض جميع السوائل',
    'liquids.createCustomMix': 'إنشاء خلطة مخصصة',
    'liquids.createCustomMixTitle': 'أنشئ خلطتك المخصصة',
    'liquids.customMixDesc': 'خلطة مخصصة مع النكهات المختارة',
    'liquids.selectFlavor': 'اختر النكهة',
    'liquids.percentage': 'النسبة المئوية',
    'liquids.ml': 'مل',
    'liquids.mg': 'ملغ',
    'liquids.allCategories': 'جميع الفئات',
    'liquids.beverage': 'مشروبات',
    'liquids.brand': 'العلامة التجارية',
    'liquids.category': 'الفئة',
    'liquids.search': 'البحث في السوائل...',
    'liquids.filters': 'المرشحات',
    'liquids.sortBy': 'ترتيب حسب',
    'liquids.sortByName': 'الاسم',
    'liquids.sortByPrice': 'السعر',
    'liquids.sortByBrand': 'العلامة التجارية',
    'liquids.sortByCategory': 'الفئة',
    'liquids.price': 'السعر',
    'liquids.stock': 'المخزون',
    'liquids.description': 'الوصف',
    'liquids.compatibility': 'التوافق',
    'liquids.analysis': 'التحليل',
    'liquids.flavorProfile': 'ملف النكهة',
    'liquids.chemicalProfile': 'الملف الكيميائي',
    'liquids.mixingRecommendations': 'توصيات الخلط',
    
    // Smart Mix System
    'mix.title': 'النظام الذكي لخلط السوائل',
    'mix.smartSuggestions': 'الاقتراحات الذكية',
    'mix.customMix': 'الخلط المخصص',
    'mix.tellUsWhat': 'أخبرنا ماذا تريد أن تتذوق',
    'mix.desiredFlavor': 'النكهة المطلوبة',
    'mix.mentholLevel': 'مستوى المنثول (0-10)',
    'mix.sweetness': 'الحلاوة (0-10)',
    'mix.complexity': 'التعقيد (0-10)',
    'mix.maxLiquids': 'الحد الأقصى للسوائل',
    'mix.getSuggestions': 'احصل على الاقتراحات',
    'mix.gettingSuggestions': 'جاري الحصول على الاقتراحات...',
    'mix.suggestedMixes': 'الخلطات المقترحة',
    'mix.createCustomMix': 'أنشئ خلطتك المخصصة',
    'mix.addLiquid': 'أضف سائل',
    'mix.analyzeMix': 'حلل الخلطة',
    'mix.analyzing': 'جاري التحليل...',
    'mix.mixAnalysis': 'تحليل الخلطة',
    'mix.estimatedProfile': 'الملف الشخصي المتوقع',
    'mix.warnings': 'تحذيرات',
    'mix.recommendations': 'توصيات',
    'mix.excellent': 'ممتاز',
    'mix.good': 'جيد',
    'mix.fair': 'متوسط',
    'mix.poor': 'ضعيف',
    'mix.menthol': 'المنثول',
    'mix.intensity': 'القوة',
    'mix.difficulty': 'الصعوبة',
    'mix.easy': 'سهل',
    'mix.medium': 'متوسط',
    'mix.hard': 'صعب',
    'mix.none': 'لا شيء',
    'mix.strong': 'قوي',
    'mix.bitter': 'مر',
    'mix.sweet': 'حلو',
    'mix.simple': 'بسيط',
    'mix.complex': 'معقد',
    'mix.selectLiquid': 'اختر السائل',
    'mix.totalPercentage': 'النسبة المئوية الإجمالية يجب أن تساوي 100%',
    'mix.addAtLeastOne': 'يرجى إضافة سائل واحد على الأقل إلى خلطتك',
    'mix.maxFiveLiquids': 'الحد الأقصى 5 سوائل مسموح',
    'mix.fruit': 'فواكه',
    'mix.dessert': 'حلويات',
    'mix.tobacco': 'تبغ',
    'mix.cream': 'كريم',
    'mix.spice': 'توابل',
    'mix.liquids': 'السوائل',
    'mix.compatibility': 'التوافق',
    'mix.selectAllLiquids': 'يرجى تحديد جميع السوائل',
    'mix.analysisFailed': 'فشل في تحليل الخلطة',
    'mix.noLiquidsAvailable': 'لا توجد سوائل متاحة',
    'mix.contactAdmin': 'يرجى التواصل مع الإدارة',
    'mix.noLiquidsInDatabase': 'لا توجد سوائل في قاعدة البيانات',
    'mix.adminMustAddLiquids': 'يجب على الإدارة إضافة سوائل أولاً',
    'mix.suggestionsFailed': 'فشل في الحصول على الاقتراحات',
    
    // Products
    'products.title': 'منتجاتنا',
    'products.all': 'جميع المنتجات',
    'products.allCategories': 'جميع الفئات',
    'products.noProducts': 'لا توجد منتجات متاحة حالياً.',
    'products.sortBy': 'ترتيب حسب',
    'products.sortByName': 'الاسم',
    'products.sortByPrice': 'السعر',
    'products.sortByStock': 'المخزون',
    'products.priceAsc': 'السعر: من الأقل إلى الأعلى',
    'products.priceDesc': 'السعر: من الأعلى إلى الأقل',
    'products.nameAsc': 'الإسم: أ-ي',
    'products.nameDesc': 'الإسم: ي-أ',
    'products.loading': 'جاري تحميل المنتجات...',
    'products.error': 'خطأ في تحميل المنتجات',
    'products.retry': 'حاول مرة أخرى',
    
    // Stores
    'stores.title': 'متاجرنا',
    'stores.findNearest': 'ابحث عن أقرب فرع من Vape Capitole إليك واكتشف تشكيلتنا الواسعة من المنتجات',
    'stores.noStores': 'لا توجد متاجر متاحة',
    'stores.noStoresDesc': 'لا توجد متاجر متاحة في الوقت الحالي.',
    'stores.location': 'الموقع',
    'stores.contact': 'التواصل',
    'stores.workingHours': 'ساعات العمل',
    'stores.viewProducts': 'عرض المنتجات',
    'stores.directions': 'الاتجاهات',
    'stores.errorFetch': 'خطأ في جلب المتاجر',
    
    // Store Details
    'store.viewProducts': 'عرض المنتجات',
    'store.products': 'المنتجات',
    'store.availableProducts': 'المنتجات المتوفرة',
    'store.noProducts': 'لا توجد منتجات متوفرة في هذا المتجر.',
    'store.getDirections': 'احصل على الاتجاهات',
    'store.contactInfo': 'معلومات التواصل',
    'store.notFound': 'المتجر غير موجود',
    'store.productsComingSoon': 'سيتم إضافة المنتجات المتوفرة في هذا المتجر قريباً',
    
    // Admin
    'admin.dashboard': 'لوحة التحكم',
    'admin.products': 'المنتجات',
    'admin.stores': 'المتاجر',
    'admin.users': 'المستخدمين',
    'admin.orders': 'الطلبات',
    'admin.translations': 'الترجمات',
    'admin.settings': 'الإعدادات',
    'admin.addProduct': 'إضافة منتج',
    'admin.editProduct': 'تعديل المنتج',
    'admin.deleteProduct': 'حذف المنتج',
    'admin.saveChanges': 'حفظ التغييرات',
    'admin.cancel': 'إلغاء',
    'admin.selectCategory': 'اختر الفئة',
    'admin.selectStore': 'اختر المتجر',
    'admin.name': 'الاسم',
    'admin.description': 'الوصف',
    'admin.price': 'السعر',
    'admin.stock': 'المخزون',
    'admin.category': 'الفئة',
    'admin.store': 'المتجر',
    'admin.image': 'الصورة',
    'admin.actions': 'الإجراءات',
    'admin.edit': 'تعديل',
    'admin.delete': 'حذف',
    'admin.confirmDelete': 'هل أنت متأكد من حذف هذا العنصر؟',
    'admin.yes': 'نعم',
    'admin.no': 'لا',
    'admin.search': 'بحث',
    'admin.searchPlaceholder': 'ابحث في المنتجات...',
    'admin.loading': 'جاري التحميل...',
    'admin.error': 'خطأ',
    'admin.success': 'نجح',
    'admin.failed': 'فشل',
    
    // Cart & Favorites
    'cart.title': 'سلة التسوق',
    'cart.empty': 'سلة التسوق فارغة',
    'cart.addItems': 'أضف منتجات إلى سلة التسوق',
    'cart.quantity': 'الكمية',
    'cart.total': 'الإجمالي',
    'cart.checkout': 'إتمام الشراء',
    'cart.remove': 'إزالة',
    'cart.update': 'تحديث',
    'cart.items': 'عناصر',
    'cart.item': 'عنصر',
    'cart.subtotal': 'المجموع الفرعي',
    'cart.shipping': 'الشحن',
    'cart.tax': 'الضريبة',
    'cart.grandTotal': 'المجموع الكلي',
    
    'favorites.title': 'المفضلة',
    'favorites.empty': 'لا توجد عناصر في المفضلة',
    'favorites.addItems': 'أضف منتجات إلى المفضلة',
    'favorites.remove': 'إزالة من المفضلة',
    'favorites.add': 'إضافة إلى المفضلة',
    
    // Checkout
    'checkout.title': 'إتمام الشراء',
    'checkout.orderSummary': 'ملخص الطلب',
    'checkout.shippingInfo': 'معلومات الشحن',
    'checkout.quantity': 'الكمية',
    'checkout.street': 'عنوان الشارع',
    'checkout.city': 'المدينة',
    'checkout.state': 'الولاية',
    'checkout.zipCode': 'الرمز البريدي',
    'checkout.country': 'البلد',
    'checkout.paymentMethod': 'طريقة الدفع',
    'checkout.cashOnDelivery': 'الدفع عند الاستلام',
    'checkout.creditCard': 'بطاقة ائتمان',
    'checkout.placeOrder': 'إتمام الطلب',
    'checkout.processing': 'جاري المعالجة...',
    'checkout.loginRequired': 'يرجى تسجيل الدخول لإتمام طلبك',
    'checkout.orderFailed': 'فشل في إنشاء الطلب',
    'checkout.addProductsFirst': 'أضف بعض المنتجات إلى سلة التسوق قبل إتمام الشراء',
    'checkout.continueShopping': 'مواصلة التسوق',
    'checkout.freeShipping': 'شحن مجاني',
    
    // Search
    'search.placeholder': 'البحث في المنتجات والسوائل...',
    'search.product': 'منتج',
    'search.liquid': 'سائل',
    'search.noResults': 'لا توجد نتائج',
    'search.searching': 'جاري البحث...',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.add': 'إضافة',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.view': 'عرض',
    'common.details': 'التفاصيل',
    'common.close': 'إغلاق',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.submit': 'إرسال',
    'common.reset': 'إعادة تعيين',
    'common.confirm': 'تأكيد',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.ok': 'موافق',
    'common.currency': 'دج',
    'common.pieces': 'قطع',
    'common.available': 'متوفر',
    'common.notAvailable': 'غير متوفر',
    'common.outOfStock': 'نفذ من المخزون',
    'common.inStock': 'متوفر في المخزون',
    'common.selectStores': 'اختر المتاجر',
    'common.noStoresAvailable': 'لا توجد متاجر متاحة',
    'common.noStoresAssigned': 'لا توجد متاجر معينة',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.stores': 'Stores',
    'nav.favorites': 'Favorites',
    'nav.liquids': 'Liquids',
    'nav.mix': 'Smart Mix',
    
    // Categories
    'category.vape-kits': 'Complete Vape Device',
    'category.vape-boxes': 'Vape Box',
    'category.atomizers': 'Atomizer',
    'category.pyrex': 'Pyrex',
    'category.accus': 'Vape Batteries',
    'category.accessories': 'Vape Accessories',
    'category.cotton': 'Cotton',
    'category.coils': 'Coils',
    'category.resistors': 'Resistors',
    
    // Product details
    'product.addToCart': 'Add to Cart',
    'product.available': 'Available',
    'product.notAvailable': 'Not Available',
    'product.price': 'Price',
    'product.stock': 'Stock',
    'product.description': 'Description',
    'product.category': 'Category',
    'product.viewDetails': 'View Details',
    'product.outOfStock': 'Out of Stock',
    'product.inStock': 'In Stock',
    'product.pieces': 'pieces',
    'product.notFound': 'Product not found',
    'product.availableInStores': 'Available in stores',
    'product.availableInBranches': 'Available in branches',
    
    // Store details
    'store.location': 'Location',
    'store.contact': 'Contact',
    'store.directions': 'Directions',
    'store.workingHours': 'Working Hours',
    
    // Theme
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    
    // Language
    'lang.ar': 'العربية',
    'lang.en': 'English',
    'lang.fr': 'Français',
    
    // Home
    'home.title': 'Welcome to Vape Shop',
    'home.subtitle': 'Everything you need for vaping in one place',
    'home.stores': 'Our Branches',
    'home.storesDesc': 'Find the nearest branch to you',
    'home.products': 'Products',
    'home.productsDesc': 'Browse all devices and accessories',
    'home.liquids': 'Flavors & Liquids',
    'home.liquidsDesc': 'Explore flavors and mix your own',
    'home.welcome': 'Welcome to',
    'home.vapeCapitole': 'Vape Capitole',
    'home.discover': 'Discover our wide collection',
    'home.quality': 'High quality and competitive prices',
    
    // Footer
    'footer.title': 'Vape Shop',
    'footer.subtitle': 'Everything you need for vaping in one place',
    'footer.quickLinks': 'Quick Links',
    'footer.home': 'Home',
    'footer.products': 'Products',
    'footer.liquids': 'Liquids',
    'footer.contact': 'Contact Us',
    'footer.email': 'Email',
    'footer.phone': 'Phone',
    'footer.rights': 'All rights reserved.',
    'footer.followUs': 'Follow Us',
    'footer.newsletter': 'Newsletter',
    'footer.subscribe': 'Subscribe',
    'footer.subscribeDesc': 'Get the latest offers and updates',
    
    // Liquids & MixLiquids
    'liquids.title': 'Flavors & Liquids',
    'liquids.customMix': 'Custom Mix',
    'liquids.customMixBtn': 'Mix Your Own',
    'liquids.createMix': 'Create Your Mix',
    'liquids.chooseFlavors': 'Choose Flavors (Max 3)',
    'liquids.nicotine': 'Nicotine Level',
    'liquids.volume': 'Volume',
    'liquids.vgpg': 'VG/PG Ratio',
    'liquids.total': 'Total',
    'liquids.priceNote': 'Base price + 2 DZD per additional flavor',
    'liquids.addToCart': 'Add to Cart',
    'liquids.noLiquids': 'No liquids available at the moment.',
    'liquids.flavors': 'Flavors',
    'liquids.inStock': 'In Stock',
    'liquids.outOfStock': 'Out of Stock',
    'liquids.viewAll': 'View All Liquids',
    'liquids.createCustomMix': 'Create Custom Mix',
    'liquids.createCustomMixTitle': 'Create Your Custom Mix',
    'liquids.customMixDesc': 'Custom mix with selected flavors',
    'liquids.selectFlavor': 'Select Flavor',
    'liquids.percentage': 'Percentage',
    'liquids.ml': 'ml',
    'liquids.mg': 'mg',
    'liquids.allCategories': 'All Categories',
    'liquids.beverage': 'Beverages',
    'liquids.brand': 'Brand',
    'liquids.category': 'Category',
    'liquids.search': 'Search Liquids...',
    'liquids.filters': 'Filters',
    'liquids.sortBy': 'Sort by',
    'liquids.sortByName': 'Name',
    'liquids.sortByPrice': 'Price',
    'liquids.sortByBrand': 'Brand',
    'liquids.sortByCategory': 'Category',
    'liquids.price': 'Price',
    'liquids.stock': 'Stock',
    'liquids.description': 'Description',
    'liquids.compatibility': 'Compatibility',
    'liquids.analysis': 'Analysis',
    'liquids.flavorProfile': 'Flavor Profile',
    'liquids.chemicalProfile': 'Chemical Profile',
    'liquids.mixingRecommendations': 'Mixing Recommendations',
    
    // Smart Mix System
    'mix.title': 'Smart Liquid Mixing System',
    'mix.smartSuggestions': 'Smart Suggestions',
    'mix.customMix': 'Custom Mix',
    'mix.tellUsWhat': 'Tell us what you want to taste',
    'mix.desiredFlavor': 'Desired Flavor',
    'mix.mentholLevel': 'Menthol Level (0-10)',
    'mix.sweetness': 'Sweetness (0-10)',
    'mix.complexity': 'Complexity (0-10)',
    'mix.maxLiquids': 'Maximum Liquids',
    'mix.getSuggestions': 'Get Suggestions',
    'mix.gettingSuggestions': 'Getting suggestions...',
    'mix.suggestedMixes': 'Suggested Mixes',
    'mix.createCustomMix': 'Create Your Custom Mix',
    'mix.addLiquid': 'Add Liquid',
    'mix.analyzeMix': 'Analyze Mix',
    'mix.analyzing': 'Analyzing...',
    'mix.mixAnalysis': 'Mix Analysis',
    'mix.estimatedProfile': 'Estimated Profile',
    'mix.warnings': 'Warnings',
    'mix.recommendations': 'Recommendations',
    'mix.excellent': 'Excellent',
    'mix.good': 'Good',
    'mix.fair': 'Fair',
    'mix.poor': 'Poor',
    'mix.menthol': 'Menthol',
    'mix.intensity': 'Intensity',
    'mix.difficulty': 'Difficulty',
    'mix.easy': 'Easy',
    'mix.medium': 'Medium',
    'mix.hard': 'Hard',
    'mix.none': 'None',
    'mix.strong': 'Strong',
    'mix.bitter': 'Bitter',
    'mix.sweet': 'Sweet',
    'mix.simple': 'Simple',
    'mix.complex': 'Complex',
    'mix.selectLiquid': 'Select Liquid',
    'mix.totalPercentage': 'Total percentage must equal 100%',
    'mix.addAtLeastOne': 'Please add at least one liquid to your mix',
    'mix.maxFiveLiquids': 'Maximum 5 liquids allowed',
    'mix.fruit': 'Fruit',
    'mix.dessert': 'Dessert',
    'mix.tobacco': 'Tobacco',
    'mix.cream': 'Cream',
    'mix.spice': 'Spice',
    'mix.liquids': 'Liquids',
    'mix.compatibility': 'Compatibility',
    'mix.selectAllLiquids': 'Please select all liquids',
    'mix.analysisFailed': 'Mix analysis failed',
    
    // Products
    'products.title': 'Our Products',
    'products.all': 'All Products',
    'products.allCategories': 'All Categories',
    'products.noProducts': 'No products available at the moment.',
    'products.sortBy': 'Sort by',
    'products.sortByName': 'Name',
    'products.sortByPrice': 'Price',
    'products.sortByStock': 'Stock',
    'products.priceAsc': 'Price: Low to High',
    'products.priceDesc': 'Price: High to Low',
    'products.nameAsc': 'Name: A-Z',
    'products.nameDesc': 'Name: Z-A',
    'products.loading': 'Loading products...',
    'products.error': 'Error loading products',
    'products.retry': 'Retry',
    
    // Stores
    'stores.title': 'Our Stores',
    'stores.findNearest': 'Find the nearest Vape Capitole branch to you and discover our wide selection of products',
    'stores.noStores': 'No stores available',
    'stores.noStoresDesc': 'No stores available at the moment.',
    'stores.location': 'Location',
    'stores.contact': 'Contact',
    'stores.workingHours': 'Working Hours',
    'stores.viewProducts': 'View Products',
    'stores.directions': 'Directions',
    'stores.errorFetch': 'Error fetching stores',
    
    // Store Details
    'store.address': 'Address',
    'store.phone': 'Phone',
    'store.hours': 'Working Hours',
    'store.viewProducts': 'View Products',
    'store.products': 'Products',
    'store.availableProducts': 'Available Products',
    'store.noProducts': 'No products available in this store.',
    'store.getDirections': 'Get Directions',
    'store.contactInfo': 'Contact Information',
    'store.notFound': 'Store not found',
    'store.productsComingSoon': 'Products available in this store will be added soon',
    
    // Admin
    'admin.dashboard': 'Dashboard',
    'admin.products': 'Products',
    'admin.stores': 'Stores',
    'admin.users': 'Users',
    'admin.orders': 'Orders',
    'admin.translations': 'Translations',
    'admin.settings': 'Settings',
    'admin.addProduct': 'Add Product',
    'admin.editProduct': 'Edit Product',
    'admin.deleteProduct': 'Delete Product',
    'admin.saveChanges': 'Save Changes',
    'admin.cancel': 'Cancel',
    'admin.selectCategory': 'Select Category',
    'admin.selectStore': 'Select Store',
    'admin.name': 'Name',
    'admin.description': 'Description',
    'admin.price': 'Price',
    'admin.stock': 'Stock',
    'admin.category': 'Category',
    'admin.store': 'Store',
    'admin.image': 'Image',
    'admin.actions': 'Actions',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.confirmDelete': 'Are you sure you want to delete this item?',
    'admin.yes': 'Yes',
    'admin.no': 'No',
    'admin.search': 'Search',
    'admin.searchPlaceholder': 'Search products...',
    'admin.loading': 'Loading...',
    'admin.error': 'Error',
    'admin.success': 'Success',
    'admin.failed': 'Failed',
    
    // Cart & Favorites
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.addItems': 'Add items to your cart',
    'cart.quantity': 'Quantity',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.remove': 'Remove',
    'cart.update': 'Update',
    'cart.items': 'items',
    'cart.item': 'item',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.tax': 'Tax',
    'cart.grandTotal': 'Grand Total',
    
    'favorites.title': 'Favorites',
    'favorites.empty': 'No items in favorites',
    'favorites.addItems': 'Add items to favorites',
    'favorites.remove': 'Remove from favorites',
    'favorites.add': 'Add to favorites',
    
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.orderSummary': 'Order Summary',
    'checkout.shippingInfo': 'Shipping Information',
    'checkout.quantity': 'Quantity',
    'checkout.street': 'Street Address',
    'checkout.city': 'City',
    'checkout.state': 'State',
    'checkout.zipCode': 'Zip Code',
    'checkout.country': 'Country',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.cashOnDelivery': 'Cash on Delivery',
    'checkout.creditCard': 'Credit Card',
    'checkout.placeOrder': 'Place Order',
    'checkout.processing': 'Processing...',
    'checkout.loginRequired': 'Please log in to complete your order',
    'checkout.orderFailed': 'Order creation failed',
    'checkout.addProductsFirst': 'Add some products to your cart before completing the purchase',
    'checkout.continueShopping': 'Continue Shopping',
    'checkout.freeShipping': 'Free Shipping',
    
    // Search
    'search.placeholder': 'Search products and liquids...',
    'search.product': 'Product',
    'search.liquid': 'Liquid',
    'search.noResults': 'No results found',
    'search.searching': 'Searching...',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.view': 'View',
    'common.details': 'Details',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.currency': 'DZD',
    'common.pieces': 'pieces',
    'common.available': 'Available',
    'common.notAvailable': 'Not Available',
    'common.outOfStock': 'Out of Stock',
    'common.inStock': 'In Stock',
    'common.selectStores': 'Select Stores',
    'common.noStoresAvailable': 'No stores available',
    'common.noStoresAssigned': 'No stores assigned',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.products': 'Produits',
    'nav.stores': 'Magasins',
    'nav.favorites': 'Favoris',
    'nav.liquids': 'Liquides',
    'nav.mix': 'Mélange Intelligent',
    
    // Categories
    'category.vape-kits': 'Appareil Vape Complet',
    'category.vape-boxes': 'Vape Box',
    'category.atomizers': 'Atomizer',
    'category.pyrex': 'Pyrex',
    'category.accus': 'Batteries Vape',
    'category.accessories': 'Accessoires Vape',
    'category.cotton': 'Coton',
    'category.coils': 'Bobines',
    'category.resistors': 'Résistances',
    
    // Product details
    'product.addToCart': 'Ajouter au Panier',
    'product.available': 'Disponible',
    'product.notAvailable': 'Non Disponible',
    'product.price': 'Prix',
    'product.stock': 'Stock',
    'product.description': 'Description',
    'product.category': 'Catégorie',
    'product.viewDetails': 'Voir les Détails',
    'product.outOfStock': 'Rupture de Stock',
    'product.inStock': 'En Stock',
    'product.pieces': 'pièces',
    'product.notFound': 'Produit non trouvé',
    'product.availableInStores': 'Disponible en magasins',
    'product.availableInBranches': 'Disponible en succursales',
    
    // Store details
    'store.location': 'Emplacement',
    'store.contact': 'Contact',
    'store.directions': 'Directions',
    'store.workingHours': 'Heures de Travail',
    
    // Theme
    'theme.light': 'Clair',
    'theme.dark': 'Sombre',
    
    // Language
    'lang.ar': 'العربية',
    'lang.en': 'English',
    'lang.fr': 'Français',
    
    // Home
    'home.title': 'Bienvenue dans la Boutique Vape',
    'home.subtitle': 'Tout ce dont vous avez besoin pour le vapotage en un seul endroit',
    'home.stores': 'Nos Succursales',
    'home.storesDesc': 'Trouvez la succursale la plus proche',
    'home.products': 'Produits',
    'home.productsDesc': 'Parcourez tous les appareils et accessoires',
    'home.liquids': 'Saveurs et Liquides',
    'home.liquidsDesc': 'Explorez les saveurs et mélangez les vôtres',
    'home.welcome': 'Bienvenue à',
    'home.vapeCapitole': 'Vape Capitole',
    'home.discover': 'Découvrez notre large collection',
    'home.quality': 'Qualité élevée et prix compétitifs',
    
    // Footer
    'footer.title': 'Boutique Vape',
    'footer.subtitle': 'Tout ce dont vous avez besoin pour le vapotage en un seul endroit',
    'footer.quickLinks': 'Liens Rapides',
    'footer.home': 'Accueil',
    'footer.products': 'Produits',
    'footer.liquids': 'Liquides',
    'footer.contact': 'Contactez-nous',
    'footer.email': 'Email',
    'footer.phone': 'Téléphone',
    'footer.rights': 'Tous droits réservés.',
    'footer.followUs': 'Suivez-nous',
    'footer.newsletter': 'Newsletter',
    'footer.subscribe': 'S\'abonner',
    'footer.subscribeDesc': 'Obtenez les dernières offres et mises à jour',
    
    // Liquids & MixLiquids
    'liquids.title': 'Saveurs et Liquides',
    'liquids.customMix': 'Mélange Personnalisé',
    'liquids.customMixBtn': 'Mélangez le Vôtre',
    'liquids.createMix': 'Créez Votre Mélange',
    'liquids.chooseFlavors': 'Choisissez les Saveurs (Max 3)',
    'liquids.nicotine': 'Niveau de Nicotine',
    'liquids.volume': 'Volume',
    'liquids.vgpg': 'Ratio VG/PG',
    'liquids.total': 'Total',
    'liquids.priceNote': 'Prix de base + 2 DZD par saveur supplémentaire',
    'liquids.addToCart': 'Ajouter au Panier',
    'liquids.noLiquids': 'Aucun liquide disponible pour le moment.',
    'liquids.flavors': 'Saveurs',
    'liquids.inStock': 'En Stock',
    'liquids.outOfStock': 'Rupture de Stock',
    'liquids.viewAll': 'Voir Tous les Liquides',
    'liquids.createCustomMix': 'Créer un Mélange Personnalisé',
    'liquids.createCustomMixTitle': 'Créez Votre Mélange Personnalisé',
    'liquids.customMixDesc': 'Mélange personnalisé avec les saveurs sélectionnées',
    'liquids.selectFlavor': 'Sélectionner la Saveur',
    'liquids.percentage': 'Pourcentage',
    'liquids.ml': 'ml',
    'liquids.mg': 'mg',
    'liquids.allCategories': 'Toutes les Catégories',
    'liquids.beverage': 'Boissons',
    'liquids.brand': 'Marque',
    'liquids.category': 'Catégorie',
    'liquids.search': 'Rechercher des Liquides...',
    'liquids.filters': 'Filtres',
    'liquids.sortBy': 'Trier par',
    'liquids.sortByName': 'Nom',
    'liquids.sortByPrice': 'Prix',
    'liquids.sortByBrand': 'Marque',
    'liquids.sortByCategory': 'Catégorie',
    'liquids.price': 'Prix',
    'liquids.stock': 'Stock',
    'liquids.description': 'Description',
    'liquids.compatibility': 'Compatibilité',
    'liquids.analysis': 'Analyse',
    'liquids.flavorProfile': 'Profil de Saveur',
    'liquids.chemicalProfile': 'Profil Chimique',
    'liquids.mixingRecommendations': 'Recommandations de Mélange',
    
    // Smart Mix System
    'mix.title': 'Système de Mélange Intelligent',
    'mix.smartSuggestions': 'Suggestions Intelligentes',
    'mix.customMix': 'Mélange Personnalisé',
    'mix.tellUsWhat': 'Dites-nous ce que vous voulez goûter',
    'mix.desiredFlavor': 'Saveur Souhaitée',
    'mix.mentholLevel': 'Niveau de Menthol (0-10)',
    'mix.sweetness': 'Douceur (0-10)',
    'mix.complexity': 'Complexité (0-10)',
    'mix.maxLiquids': 'Liquides Maximum',
    'mix.getSuggestions': 'Obtenir des Suggestions',
    'mix.gettingSuggestions': 'Obtention des suggestions...',
    'mix.suggestedMixes': 'Mélanges Suggérés',
    'mix.createCustomMix': 'Créez Votre Mélange Personnalisé',
    'mix.addLiquid': 'Ajouter un Liquide',
    'mix.analyzeMix': 'Analyser le Mélange',
    'mix.analyzing': 'Analyse en cours...',
    'mix.mixAnalysis': 'Analyse du Mélange',
    'mix.estimatedProfile': 'Profil Estimé',
    'mix.warnings': 'Avertissements',
    'mix.recommendations': 'Recommandations',
    'mix.excellent': 'Excellent',
    'mix.good': 'Bon',
    'mix.fair': 'Moyen',
    'mix.poor': 'Faible',
    'mix.menthol': 'Menthol',
    'mix.intensity': 'Intensité',
    'mix.difficulty': 'Difficulté',
    'mix.easy': 'Facile',
    'mix.medium': 'Moyen',
    'mix.hard': 'Difficile',
    'mix.none': 'Aucun',
    'mix.strong': 'Fort',
    'mix.bitter': 'Amer',
    'mix.sweet': 'Doux',
    'mix.simple': 'Simple',
    'mix.complex': 'Complexe',
    'mix.selectLiquid': 'Sélectionner le Liquide',
    'mix.totalPercentage': 'Le pourcentage total doit être égal à 100%',
    'mix.addAtLeastOne': 'Veuillez ajouter au moins un liquide à votre mélange',
    'mix.maxFiveLiquids': 'Maximum 5 liquides autorisés',
    'mix.fruit': 'Fruit',
    'mix.dessert': 'Dessert',
    'mix.tobacco': 'Tabac',
    'mix.cream': 'Crème',
    'mix.spice': 'Épice',
    'mix.liquids': 'Liquides',
    'mix.compatibility': 'Compatibilité',
    'mix.selectAllLiquids': 'Veuillez sélectionner tous les liquides',
    'mix.analysisFailed': 'Échec de l\'analyse de mélange',
    'mix.noLiquidsAvailable': 'Aucun liquide disponible pour le moment.',
    'mix.contactAdmin': 'Veuillez contacter l\'administrateur.',
    'mix.noLiquidsInDatabase': 'Aucune liquide trouvée dans la base de données.',
    'mix.adminMustAddLiquids': 'L\'administrateur doit d\'abord ajouter des liquides.',
    
    // Products
    'products.title': 'Nos Produits',
    'products.all': 'Tous les Produits',
    'products.allCategories': 'Toutes les Catégories',
    'products.noProducts': 'Aucun produit disponible pour le moment.',
    'products.sortBy': 'Trier par',
    'products.sortByName': 'Nom',
    'products.sortByPrice': 'Prix',
    'products.sortByStock': 'Stock',
    'products.priceAsc': 'Prix: Croissant',
    'products.priceDesc': 'Prix: Décroissant',
    'products.nameAsc': 'Nom: A-Z',
    'products.nameDesc': 'Nom: Z-A',
    'products.loading': 'Chargement des produits...',
    'products.error': 'Erreur de chargement des produits',
    'products.retry': 'Réessayer',
    
    // Stores
    'stores.title': 'Nos Magasins',
    'stores.findNearest': 'Trouvez la succursale Vape Capitole la plus proche de vous et découvrez notre large sélection de produits',
    'stores.noStores': 'Aucun magasin disponible',
    'stores.noStoresDesc': 'Aucun magasin disponible pour le moment.',
    'stores.location': 'Emplacement',
    'stores.contact': 'Contact',
    'stores.workingHours': 'Heures de Travail',
    'stores.viewProducts': 'Voir les Produits',
    'stores.directions': 'Directions',
    'stores.errorFetch': 'Erreur lors du chargement des magasins',
    
    // Store Details
    'store.address': 'Adresse',
    'store.phone': 'Téléphone',
    'store.hours': 'Heures de Travail',
    'store.viewProducts': 'Voir les Produits',
    'store.products': 'Produits',
    'store.availableProducts': 'Produits Disponibles',
    'store.noProducts': 'Aucun produit disponible dans ce magasin.',
    'store.getDirections': 'Obtenir les Directions',
    'store.contactInfo': 'Informations de Contact',
    'store.notFound': 'Magasin non trouvé',
    'store.productsComingSoon': 'Les produits disponibles dans ce magasin seront ajoutés prochainement',
    
    // Admin
    'admin.dashboard': 'Tableau de Bord',
    'admin.products': 'Produits',
    'admin.stores': 'Magasins',
    'admin.users': 'Utilisateurs',
    'admin.orders': 'Commandes',
    'admin.translations': 'Traductions',
    'admin.settings': 'Paramètres',
    'admin.addProduct': 'Ajouter un Produit',
    'admin.editProduct': 'Modifier le Produit',
    'admin.deleteProduct': 'Supprimer le Produit',
    'admin.saveChanges': 'Enregistrer les Modifications',
    'admin.cancel': 'Annuler',
    'admin.selectCategory': 'Sélectionner la Catégorie',
    'admin.selectStore': 'Sélectionner le Magasin',
    'admin.name': 'Nom',
    'admin.description': 'Description',
    'admin.price': 'Prix',
    'admin.stock': 'Stock',
    'admin.category': 'Catégorie',
    'admin.store': 'Magasin',
    'admin.image': 'Image',
    'admin.actions': 'Actions',
    'admin.edit': 'Modifier',
    'admin.delete': 'Supprimer',
    'admin.confirmDelete': 'Êtes-vous sûr de vouloir supprimer cet élément ?',
    'admin.yes': 'Oui',
    'admin.no': 'Non',
    'admin.search': 'Rechercher',
    'admin.searchPlaceholder': 'Rechercher des produits...',
    'admin.loading': 'Chargement...',
    'admin.error': 'Erreur',
    'admin.success': 'Succès',
    'admin.failed': 'Échec',
    
    // Cart & Favorites
    'cart.title': 'Panier d\'Achat',
    'cart.empty': 'Votre panier est vide',
    'cart.addItems': 'Ajoutez des articles à votre panier',
    'cart.quantity': 'Quantité',
    'cart.total': 'Total',
    'cart.checkout': 'Commander',
    'cart.remove': 'Supprimer',
    'cart.update': 'Mettre à jour',
    'cart.items': 'articles',
    'cart.item': 'article',
    'cart.subtotal': 'Sous-total',
    'cart.shipping': 'Livraison',
    'cart.tax': 'Taxe',
    'cart.grandTotal': 'Total Général',
    
    'favorites.title': 'Favoris',
    'favorites.empty': 'Aucun article dans les favoris',
    'favorites.addItems': 'Ajoutez des articles aux favoris',
    'favorites.remove': 'Retirer des favoris',
    'favorites.add': 'Ajouter aux favoris',
    
    // Checkout
    'checkout.title': 'Commander',
    'checkout.orderSummary': 'Résumé de la Commande',
    'checkout.shippingInfo': 'Informations de Livraison',
    'checkout.quantity': 'Quantité',
    'checkout.street': 'Adresse de la Rue',
    'checkout.city': 'Ville',
    'checkout.state': 'État',
    'checkout.zipCode': 'Code Postal',
    'checkout.country': 'Pays',
    'checkout.paymentMethod': 'Méthode de Paiement',
    'checkout.cashOnDelivery': 'Paiement à la Livraison',
    'checkout.creditCard': 'Carte de Crédit',
    'checkout.placeOrder': 'Passer la Commande',
    'checkout.processing': 'Traitement en cours...',
    'checkout.loginRequired': 'Veuillez vous connecter pour passer votre commande',
    'checkout.orderFailed': 'Échec de la création de la commande',
    'checkout.addProductsFirst': 'Ajoutez quelques produits à votre panier avant de passer la commande',
    'checkout.continueShopping': 'Continuer le Shopping',
    'checkout.freeShipping': 'Livraison Gratuite',
    
    // Search
    'search.placeholder': 'Rechercher des produits et des liquides...',
    'search.product': 'Produit',
    'search.liquid': 'Liquide',
    'search.noResults': 'Aucun résultat trouvé',
    'search.searching': 'Recherche en cours...',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.add': 'Ajouter',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.view': 'Voir',
    'common.details': 'Détails',
    'common.close': 'Fermer',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.submit': 'Soumettre',
    'common.reset': 'Réinitialiser',
    'common.confirm': 'Confirmer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.ok': 'OK',
    'common.currency': 'DZD',
    'common.pieces': 'pièces',
    'common.available': 'Disponible',
    'common.notAvailable': 'Non Disponible',
    'common.outOfStock': 'Rupture de Stock',
    'common.inStock': 'En Stock',
    'common.selectStores': 'Sélectionner les Magasins',
    'common.noStoresAvailable': 'Aucun magasin disponible',
    'common.noStoresAssigned': 'Aucun magasin assigné',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>('ar');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['ar', 'en', 'fr'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    const currentTranslations = translations[language] as Record<string, string>;
    return currentTranslations[key] || key;
  };

  // ترجمة ذكية للنص
  const translateText = async (text: string): Promise<string> => {
    if (language === 'ar') return text;
    return await smartTranslationService.translateText(text, language);
  };

  // ترجمة ذكية للمنتج
  const translateProduct = async (product: any): Promise<any> => {
    if (language === 'ar') return product;
    return await smartTranslationService.translateProduct(product, language);
  };

  // ترجمة ذكية للمتجر
  const translateStore = async (store: any): Promise<any> => {
    if (language === 'ar') return store;
    return await smartTranslationService.translateStore(store, language);
  };

  // ترجمة ذكية للسائل
  const translateLiquid = async (liquid: any): Promise<any> => {
    if (language === 'ar') return liquid;
    return await smartTranslationService.translateLiquid(liquid, language);
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage, 
      t,
      translateText,
      translateProduct,
      translateStore,
      translateLiquid
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
